<!--
Thanks for the contribution. Please fill out the sections below. PRs
with empty descriptions or missing checks will not be reviewed.
-->

## What

<!-- One paragraph: what does this PR do, in plain language? -->

## Why

<!--
The motivation. Link to an issue or describe the behaviour that
prompted the change. "Refactor" is not a why.
-->

## How

<!--
The mechanism. Note any non-obvious choices so a reviewer can
understand the trade-offs.
-->

## Testing

<!-- What did you run, locally, and what did you see? Paste output. -->

## Pre-merge checklist

- [ ] Every commit is **DCO sign-off**ed (`git commit -s`)
- [ ] Every commit is **GPG/SSH signed** (green "Verified" badge)
- [ ] Branch is rebased on the latest `main`
- [ ] Project tests pass
- [ ] The PR title follows Conventional Commits
      (`feat(scope): …` / `fix(scope): …` / `chore(scope): …` / …)
- [ ] If this PR adds a new dependency, the license is noted in `NOTICE`

## Trademark / brand confirmation

- [ ] This PR does not change the project name, mark, or domains. If
      it does, I have read `TRADEMARK.md` and have prior written
      permission.

## AI-generated contribution disclosure

- [ ] This PR was authored entirely by a human.
- [ ] This PR was substantially generated by an LLM and I have
      reviewed every change. I am taking DCO responsibility for the
      contents.
